// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKTYYVb1BY9QhJt7e5VZUf5lBhaeJmgs',
    appId: '1:838233937267:web:82fe870e374cf9bfe1e106',
    messagingSenderId: '838233937267',
    projectId: 'fluttertest-1defc',
    authDomain: 'fluttertest-1defc.firebaseapp.com',
    storageBucket: 'fluttertest-1defc.appspot.com',
    measurementId: 'G-Q217KH60NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkP0Q5fhbGydtiCGEEaJ9Itm2uuTyUZk',
    appId: '1:838233937267:android:bf534513bf6610ece1e106',
    messagingSenderId: '838233937267',
    projectId: 'fluttertest-1defc',
    storageBucket: 'fluttertest-1defc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFWOVQW3Qdteua-accJeutuGSXgjtaMc',
    appId: '1:838233937267:ios:258f7d23908e8fffe1e106',
    messagingSenderId: '838233937267',
    projectId: 'fluttertest-1defc',
    storageBucket: 'fluttertest-1defc.appspot.com',
    iosClientId: '838233937267-a3kq9bo3npu3f1afv11a5qaen5901uu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFWOVQW3Qdteua-accJeutuGSXgjtaMc',
    appId: '1:838233937267:ios:258f7d23908e8fffe1e106',
    messagingSenderId: '838233937267',
    projectId: 'fluttertest-1defc',
    storageBucket: 'fluttertest-1defc.appspot.com',
    iosClientId: '838233937267-a3kq9bo3npu3f1afv11a5qaen5901uu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );
}
